config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  
  #ユーザー登録のルーティング
  resources :signup do
    collection do
      get 'registration'
      get 'sms_confirmation'
      get 'address'
      get 'done'
    end
  end
  
  # ルート指定
  root 'tops#index'
  
  # ユーザーページのルーティング
  resources :users do
    resource :self_address
    resources :delivery_addresses
  end

  # 商品ページのルーティング
  resources :items do
    resources :likes
    resources :comments
    resources :images
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
    end
    # 購入
    resources :purchases, only: [:index] do
      collection do
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end

  # カード登録ページのルーティング
  resources :cards, only: [:create, :show, :edit] do
    collection do
      post 'delete', to: 'cards/current_user.id/delete'
      post 'show'
    end
    member do
      get 'confirmation'
    end
  end 
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  
  def index
  end

  def registration
    @user = User.new
  end

  def sms_confirmation
    session[:nickname] = user_params[:nickname]
    session[:email] = user_params[:email]
    session[:password] = user_params[:password]
    session[:password_confirmation] = user_params[:password_confirmation]
    session[:last_name] = user_params[:last_name]
    session[:first_name] = user_params[:first_name]
    session[:last_jp_name] = user_params[:last_jp_name]
    session[:first_jp_name] = user_params[:first_jp_name]
    session[:year_id] = user_params[:year_id]
    session[:month_id] = user_params[:month_id]
    session[:day_id] = user_params[:day_id]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_jp_name: session[:last_jp_name],
      first_jp_name: session[:first_jp_name],
      year_id: session[:year_id],
      month_id: session[:month_id],
      day_id: session[:day_id],
      tel: '09012345678',
      zip_code: '1234567',
      prefecture_id: '1',
      city: '札幌',
      address: '中央区',
      building: 'ビル',
      telephone: '08098765432'
    )
    render '/signup/registration' unless @user.valid?
  end

  def address
    session[:tel] = user_params[:tel]
    @user = User.new(
      nickname: session[:nickname],
      email: session[:email],
      password: session[:password],
      password_confirmation: session[:password_confirmation],
      last_name: session[:last_name],
      first_name: session[:first_name],
      last_jp_name: session[:last_jp_name],
      first_jp_name: session[:first_jp_name],
      year_id: session[:year_id],
      month_id: session[:month_id],
      day_id: session[:day_id],
      tel: '09012345678',
      zip_code: '1234567',
      prefecture_id: '1',
      city: '札幌',
      address: '中央区',
      building: 'ビル',
      telephone: '08098765432'
    )
    render '/signup/sms_confirmation' unless @user.valid?
  end

  def create
    session[:zip_code] = user_params[:zip_code]
    session[:prefecture_id] = user_params[:prefecture_id]
    session[:city] = user_params[:city]
    session[:address] = user_params[:address]
    session[:building] = user_params[:building]
    session[:telephone] = user_params[:telephone]
    @user = User.new(
    nickname: session[:nickname],
    email: session[:email],
    password: session[:password],
    password_confirmation: session[:password_confirmation],
    last_name: session[:last_name],
    first_name: session[:first_name],
    last_jp_name: session[:last_jp_name],
    first_jp_name: session[:first_jp_name],
    year_id: session[:year_id],
    month_id: session[:month_id],
    day_id: session[:day_id],
    tel: session[:tel],
    zip_code: session[:zip_code],
    prefecture_id: session[:prefecture_id],
    city: session[:city],
    address: session[:address],
    building: session[:building],
    telephone: session[:telephone]
    )
    if @user.save
      session[:id] = @user.id
      redirect_to done_signup_index_path
    else
      render '/signup/address'
    end

    if params[:sns_auth] == 'true'
      pass = Devise.friendly_token
      params[:user][:password] = pass
      params[:user][:password_confirmation] = pass
    end
    super
  end

  def done
    sign_in User.find(session[:id]) unless user_signed_in?
  end

  private
# 許可するキーを設定
  def user_params
    params.require(:user).permit(
      :nickname,
      :email,
      :password,
      :password_confirmation,
      :last_name,
      :first_name,
      :last_jp_name,
      :first_jp_name,
      :year_id,
      :month_id,
      :day_id,
      :tel,
      :zip_code,
      :prefecture_id,
      :city,
      :address,
      :building,
      :telephone
    )
  end
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/_error-messages.html.haml
- if user.errors.any?
  - unless user.valid?
    - if errors = user.errors.full_messages_for(column.to_sym)
      %ul
        - errors.each do |error|
          %li=error

app/views/signup/_footer.html.haml
%footer.signupFooter
  %nav
    %ul.clearfix
      %li
        = link_to '#' do
          プライバシポリシー
      %li
        = link_to '#' do
          フリマ利用規約
      %li
        = link_to '#' do
          特定商取引に関する表記
  = link_to '#', class: 'signupFooter__logo' do
    = image_tag 'logo-blue.png'
  %p
    %small
      ©️ FURIMA

app/views/signup/address.html.haml
.signupBody
  %header.signupHeader
    %h1
      = link_to root_path do
        = image_tag 'logo.png'
    %nav.signupHeader__progressBar.signupHeader__bar
      %ol.clearfix
        %li.signupHeader__list.signupHeader__list--through
          会員情報
          .signupHeader__progressStatus
        %li.signupHeader__list.signupHeader__list--passed
          電話番号入力
          .signupHeader__progressStatus
        %li.signupHeader__list.signupHeader__list--active
          お届け先住所入力
          .signupHeader__progressStatus
        %li.signupHeader__list
          完了
          .signupHeader__progressStatus
  %main.signupMain
    %section.signupMain__container
      %h2.signupMain__head.signupMain__head--registration
        お届け先住所入力
      .signupMain__inner.signupMain__inner--registrationForm
        = form_for @user, url: signup_index_path, method: 'POST', class: 'signupMain__inner signupMain__inner--registrationForm' do |f|
          .signupMain__content
            .signupMain__formGroup
              = f.label '郵便番号'
              %span.signupMain__formRequire 必須
              = f.text_field :zip_code, { class: 'signupMain__inputDefault', placeholder: '例) 123-4567' }
              %ul.signupMain__errorText
                = render partial: 'error-messages', locals: { user: @user, column: "zip_code"}
            .signupMain__formGroup
              = f.label '都道府県'
              %span.signupMain__formRequire 必須
              .signupMain__prefectureSelectWrap
                .signupMain__selectWrap
                  = f.collection_select :prefecture_id, Prefecture.all, :id, :name
                  %ul.signupMain__errorText
                    = render partial: 'error-messages', locals: { user: @user, column: "prefecture"}
            .signupMain__formGroup
              = f.label '市区町村'
              %span.signupMain__formRequire 必須
              = f.text_field :city, { class: 'signupMain__inputDefault', placeholder: '例) 横浜市緑区' }
              %ul.signupMain__errorText
                = render partial: 'error-messages', locals: { user: @user, column: "city"}
            .signupMain__formGroup
              = f.label '番地'
              %span.signupMain__formRequire 必須
              = f.text_field :address, { class: 'signupMain__inputDefault', placeholder: '例) 青山1-1-1' }
              %ul.signupMain__errorText
                = render partial: 'error-messages', locals: { user: @user, column: "address"}
            .signupMain__formGroup
              = f.label '建物名'
              %span.signupMain__formRequire 任意
              = f.text_field :building, { class: 'signupMain__inputDefault', placeholder: '例) 柳ビル103' }
            .signupMain__formGroup
              = f.label '電話'
              %span.signupMain__formRequire 任意
              = f.text_field :telephone, { class: 'signupMain__inputDefault', placeholder: '例) 09012345678' }
            .signupMain__formGroup
            %button.signupMain__btnDefault.signupMain__btnRed
              登録を完了する
  = render 'signup/footer'

app/views/signup/done.html.haml
.signupBody
  %header.signupHeader
    %h1
      = link_to root_path do
        = image_tag 'logo.png'
    %nav.signupHeader__progressBar.signupHeader__bar
      %ol.clearfix
        %li.signupHeader__list.signupHeader__list--through
          会員情報
          .signupHeader__progressStatus
        %li.signupHeader__list.signupHeader__list--passed
          電話番号入力
          .signupHeader__progressStatus
        %li.signupHeader__list.signupHeader__list--passed
          お届け先住所入力
          .signupHeader__progressStatus
        %li.signupHeader__list.signupHeader__list--active
          完了
          .signupHeader__progressStatus

  %main.signupMain
  %section.signupMain__container
    %h2.signupMain__head.signupMain__head--registration
      会員登録完了
    .signupMain__inner.signupMain__inner--registrationForm
      .signupMain__content
        .signupMain__textCenter
          %p.signupMain__textW
            ありがとうございます。
          %br 
          %p.signupMain__textW
            登録が完了しました。
          = link_to root_path, class: 'signupMain__btnDefault signupMain__btnRed' do
            フリマをはじめる

  = render 'signup/footer'

app/views/signup/index.html.haml
.signupBody
  %header.signupHeader
    %h1
      =link_to root_path do
        =image_tag 'logo.png'

  %main.signupMain
    %section.signupMain__container
      %h2.signupMain__head.signupMain__head--registration
        新規会員登録
      .signupMain__inner.signupMain__inner--registrationForm
        .signupMain__content
          = link_to registration_signup_index_path, class: 'signupMain__btnDefault signupMain__btnMail' do
            = icon 'far', 'envelope'
            メールアドレスで登録する
          = link_to user_facebook_omniauth_authorize_path, method: :post, class: 'signupMain__btnDefault signupMain__btnSns signupMain__btnSns--facebook' do
            = icon 'fab', 'facebook-square'
            Facebookで登録する
          = link_to user_google_oauth2_omniauth_authorize_path, method: :post, class: 'signupMain__btnDefault signupMain__btnSns signupMain__btnSns--google' do
            = icon 'fab', 'google'
            Googleで登録する

  = render 'signup/footer'

app/views/signup/registration.html.haml
.signupBody
  %header.signupHeader
    %h1
      = link_to root_path do
        = image_tag 'logo.png'
    %nav.signupHeader__progressBar.signupHeader__bar
      %ol.clearfix
        %li.signupHeader__list.signupHeader__list--active
          会員情報
          .signupHeader__progressStatus
        %li.signupHeader__list
          電話番号入力
          .signupHeader__progressStatus
        %li.signupHeader__list
          お届け先住所入力
          .signupHeader__progressStatus
        %li.signupHeader__list
          完了
          .signupHeader__progressStatus
    
  %main.signupMain
    %section.signupMain__container
      %h2.signupMain__head.signupMain__head--registration
        会員情報入力
      .signupMain__inner.signupMain__inner--registrationForm
        = form_for @user, url: sms_confirmation_signup_index_path, method: 'GET', class: 'signupMain__inner signupMain__inner--registrationForm' do |f|
          .signupMain__content
            .signupMain__formGroup
              = f.label 'ニックネーム'
              %span.signupMain__formRequire 必須
              = f.text_field :nickname, { class: 'signupMain__inputDefault', placeholder: '例) メルカリ太郎' }
              %ul.signupMain__errorText
                -# = render partial: 'error-messages', locals: { user: @user, column: "nickname"}
            .signupMain__formGroup
              = f.label 'メールアドレス'
              %span.signupMain__formRequire 必須
              = f.email_field :email, { class: 'signupMain__inputDefault', placeholder: 'PC・携帯どちらでも可'}
              %ul.signupMain__errorText
                -# = render partial: 'error-messages', locals: { user: @user, column: "email"}
            - if @sns_id.present?
              = hidden_field_tag :sns_auth, true
            - else
              .signupMain__formGroup
                = f.label 'パスワード'
                %span.signupMain__formRequire 必須
                = f.password_field :password, {class: 'signupMain__inputDefault', placeholder: '7文字以上の半角英数字'}
                %ul.signupMain__errorText
                  -# = render partial: 'error-messages', locals: { user: @user, column: "password"}
                %p.signupMain__text1
                  ※ 英字と数字の両方を含めて設定してください
              .signupMain__formGroup
                = f.label 'パスワード (確認)'
                %span.signupMain__formRequire 必須
                = f.password_field :password_confirmation, { class: 'signupMain__inputDefault', placeholder: '7文字以上の半角英数字' }
                %ul.signupMain__errorText
                  -# = render partial: 'error-messages', locals: { user: @user, column: "password_confirmation"}
            .signupMain__formGroup
              %h3.signupMain__subHead
                本人確認
              %p.signupMain__text2
                安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
            .signupMain__formGroup.signupMain__formGroup--half
              %div
                = f.label 'お名前(全角)'
                %span.signupMain__formRequire 必須
                %br
                = f.text_field :last_name, {class: 'signupMain__inputDefault signupMain__inputDefault--half', placeholder: '例) 山田'}
                = f.text_field :first_name, {class: 'signupMain__inputDefault signupMain__inputDefault--half', placeholder: '例) 彩'}
                %ul.signupMain__errorText
                  -# = render partial: 'error-messages', locals: { user: @user, column: "last_name"}
                  -# = render partial: 'error-messages', locals: { user: @user, column: "first_name"}
            .signupMain__formGroup.signupMain__formGroup--half
              %div
                = f.label 'お名前カナ(全角)'
                %span.signupMain__formRequire 必須
                %br
                = f.text_field :last_jp_name, {class: 'signupMain__inputDefault signupMain__inputDefault--half', placeholder: '例) ヤマダ'}
                = f.text_field :first_jp_name, {class: 'signupMain__inputDefault signupMain__inputDefault--half', placeholder: '例) アヤ'}
                %ul.signupMain__errorText
                  -# = render partial: 'error-messages', locals: { user: @user, column: "last_jp_name"}
                  -# = render partial: 'error-messages', locals: { user: @user, column: "first_jp_name"}
            .signupMain__formGroup
              = f.label '生年月日'
              %span.signupMain__formRequire 必須
              %br
              .signupMain__birthdaySelectWrap
                .signupMain__selectWrap
                  = f.collection_select :year_id, Year.all, :id, :year, name: 'year', prompt: '--', class: 'signupMain__selectDefault'
                %span 年
                .signupMain__selectWrap
                  = f.collection_select :month_id, Month.all, :id, :month, name: 'month', prompt: '--', class: 'signupMain__selectDefault'
                %span 月
                .signupMain__selectWrap
                  = f.collection_select :day_id, Day.all, :id, :day, name: 'day', prompt: '--', class: 'signupMain__selectDefault'
                %span 日
                %ul.signupMain__errorText
                  -# = render partial: 'error-messages', locals: { user: @user, column: "year_id"}
                  -# = render partial: 'error-messages', locals: { user: @user, column: "month_id"}
                  -# = render partial: 'error-messages', locals: { user: @user, column: "day_id"}
            .signupMain__formGroup
              %p.signupMain__text1
                ※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。
            .signupMain__formGroup
              .signupMain__textCenter
              「次へ進む」のボタンを押すことにより、
              = link_to '#', target: '_blank' do
                利用規約
              に同意したものとします
            = f.submit'次へ進む', class: 'signupMain__btnDefault signupMain__btnRed'
            .signupMain__formGroup
              .signupMain__textRight
                %p
                  = link_to '#', target: '_blank' do
                    本人情報の登録について
                    = icon 'fas', 'chevron-right'
                    
  = render 'signup/footer'

app/views/signup/sms_confirmation.html.haml
.signupBody
  %header.signupHeader
    %h1
      = link_to root_path do
        = image_tag 'logo.png'
    %nav.signupHeader__progressBar.signupHeader__bar
      %ol.clearfix
        %li.signupHeader__list.signupHeader__list--through
          会員情報
          .signupHeader__progressStatus
        %li.signupHeader__list.signupHeader__list--active
          電話番号入力
          .signupHeader__progressStatus
        %li.signupHeader__list
          お届け先住所入力
          .signupHeader__progressStatus
        %li.signupHeader__list
          完了
          .signupHeader__progressStatus
  %main.signupMain
    %section.signupMain__container
      %h2.signupMain__head.signupMain__head--registration
        電話番号の確認
      .signupMain__inner.signupMain__inner--registrationForm
        = form_for @user, url: address_signup_index_path, method: 'GET', class: 'signupMain__inner signupMain__inner--registrationForm' do |f|
          .signupMain__content
            .signupMain__formGroup
              = f.label '携帯電話の電話番号'
              %span.signupMain__formRequire 必須
              = f.text_field :tel, { class: 'signupMain__inputDefault', placeholder: '携帯電話の番号を入力' }
              %ul.signupMain__errorText
                = render partial: 'error-messages', locals: { user: @user, column: "tel"}
            .signupMain__formGroup
              = f.submit'次へ進む', class: 'signupMain__btnDefault signupMain__btnRed'
            %p.signupMain__text2
              ※電話番号は本人確認や不正利用防止のために利用します。他のユーザーに公開されることはありません。
            .signupMain__formGroup
              .signupMain__textRight
                %p
                  = link_to '#', target: '_blank' do
                    電話番号の確認が必要な理由
                    = icon 'fas', 'chevron-right'
  = render 'signup/footer'

app/views/signup/sms_confirmation_sms.html.haml
.signupBody
  %header.signupHeader
    %h1
      = link_to root_path do
        = image_tag 'logo.png'
    %nav.signupHeader__progressBar.signupHeader__bar
      %ol.clearfix
        %li.signupHeader__list.signupHeader__list--through
          会員情報
          .signupHeader__progressStatus
        %li.signupHeader__list.signupHeader__list--active
          電話番号認証
          .signupHeader__progressStatus
        %li.signupHeader__list
          お届け先住所入力
          .signupHeader__progressStatus
        %li.signupHeader__list
          完了
          .signupHeader__progressStatus
  %main.signupMain
    %section.signupMain__container
      %h2.signupMain__head.signupMain__head--registration
        電話番号認証
      .signupMain__inner.signupMain__inner--registrationForm
        = form_for @user, local: true, url: address_signup_index_path, method: 'GET', class: 'signupMain__inner signupMain__inner--registrationForm', novalidate: 'novalidate' do |f|
          .signupMain__content
            .signupMain__formGroup
              = f.label '認証番号'
              = f.number_field :tel, { class: 'signupMain__inputDefault', placeholder: '認証番号を入力' }
            %p.signupMain__text2
              SMSで届いた認証番号を入力してください
            = f.submit '認証して完了', class: 'signupMain__btnDefault signupMain__btnRed'
      .signupMain__inner.signupMain__inner--registrationForm
        .signupMain__content
          .signupMain__formGroup
            %p.signupMain__text2
              30秒たっても認証番号が届かない方へ
            %p.signupMain__text2
              電話で認証番号を聞くこともできます。
            %button.signupMain__btnDefault.signupMain__btnGry
              電話で認証番号を聞く（通話無料）
          .signupMain__formGroup
            %p.signupMain__text2
              認証番号を再送することも出来ます。もう一度電話番号を入力してください。
            %button.signupMain__btnDefault.signupMain__btnGry
              電話番号を入力する
          .signupMain__formGroup
            .signupMain__textCenter
            SMSが届かない場合は
            = link_to '#', target: '_blank' do
              SMS受信設定
            を確認して、もう一度電話番号を入力してください。
          %br
  = render 'signup/footer'