config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  
  #ユーザー登録のルーティング
  resources :signup do
    collection do
      get 'registration'
      get 'sms_confirmation'
      get 'address'
      get 'done'
    end
  end
  
  # ルート指定
  root 'tops#index'
  
  # ユーザーページのルーティング
  resources :users do
    resource :self_address
    resources :delivery_addresses
  end

  # 商品ページのルーティング
  resources :items do
    resources :likes
    resources :comments
    resources :images
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
    end
    # 購入
    resources :purchases, only: [:index] do
      collection do
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end

  # カード登録ページのルーティング
  resources :cards, only: [:create, :show, :edit] do
    collection do
      post 'delete', to: 'cards/current_user.id/delete'
      post 'show'
    end
    member do
      get 'confirmation'
    end
  end 
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.haml
.banner
  .banner__info
    %h9.banner__info__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.banner__info__text
      今すぐ無料ダウンロード！
    .banner__info__btn
      %a.banner__info__btn__appBtn
        = link_to "https://itunes.apple.com" do
          = image_tag "Download_on_the_App_Store_Badge_US-UK_blk_092917.png"
      %a.banner__info__btn__googleBtn
        = link_to "https://www.microsoft.com" do
          = image_tag "google-play-badge2.png"

app/views/shared/_footer.html.haml
%footer
  .footInner
    %ul.footInner__contents
      %li.footInner__contents__content
        %h.footInner__info
          FURIMAについて
        %ul.box
          %li.text
            = link_to "#" do
              会社概要（運営会社）
          %li.text
            = link_to "#" do
              プライバシーポリシー
          %li.text
            = link_to "#" do
              FURIMA利用規約
          %li.text
            = link_to "#" do
              ポイントに関する特約

      %li.footInner__contents__content
        %h.footInner__info
          FURIMAを見る
        %ul.box
          %li.text
            = link_to "#" do
              カテゴリー一覧
          %li.text
            = link_to "#" do
              ブランド一覧
          
      %li.footInner__contents__content
        %h.footInner__info
          ヘルプ＆ガイド
        %ul.box
          %li.text
            = link_to "#" do
              FURIMAガイド
          %li.text
            = link_to "#" do
              FURIMAロゴ利用ガイドライン
          %li.text
            = link_to "#" do
              お知らせ
  
    .footInner__logo
      = link_to root_path do
        = image_tag "logo-white.png"
    %p.text
      ©️ FURIMA


.sellBtn
  =link_to new_item_path do
    .sellBtn__text
      出品する
    = icon('fa','camera',class:"sellBtn__icon")

app/views/shared/_header.html.haml
%header
  .headInner
    .headInner__Head
      .headInner__Head__title
        =link_to root_path do
          = image_tag "logo.png"
      .headInner__Head__searchBox
        %input{type: "text",placeholder: "キーワードから探す",size:"100",class:"searchBox__input"}
        %button{type: "submit"}
          = icon('fa','search',class:"searchBox__icon")
          
    .headInner__Foot
      %ul.headInner__Foot__left
        %li.headInner__Foot__left__category
          #categoryBtn カテゴリー
          %ul.dropDown
            - @parents.each do |parent|
              %li.dropDown-list
                = link_to "#{parent.name}",items_path
                %ul.dropDown
                  - parent.children.each do |child|
                    %li.dropDown-list-cal
                      =link_to child.name
                      %ul.dropDown
                        - child.children.each do |grandchild|
                          %li.dropDown-list-cal
                            = link_to grandchild.name
        %li.headInner__Foot__left__brand
          ブランド
      %ul.headInner__Foot__right
        - if user_signed_in?
          %li.headInner__Foot__right__login
            = link_to 'マイページ', user_path(current_user)
          %li.headInner__Foot__right__signUp
            = link_to destroy_user_session_path, method: 'delete' do
              ログアウト
        - else
          %li.headInner__Foot__right__login
            = link_to 'ログイン', new_user_session_path
          %li.headInner__Foot__right__signUp
            = link_to '新規会員登録', signup_index_path

app/views/shared/_navi.html.haml
.navi
  %ul
    %li.navi__name
      = link_to root_path do
        FURIMA
    = icon("fa","chevron-right",class:"navi__icon")
    %li.navi__categoryL
      = link_to "#" do
        %p= @item.category.parent.parent.name
    = icon("fa","chevron-right",class:"navi__icon")
    %li.navi__categoryM
      = link_to "#" do
        %p= @item.category.parent.name
    = icon("fa","chevron-right",class:"navi__icon")
    %li.navi__categoryS
      = link_to "#" do
        %p= @item.category.name
    = icon("fa","chevron-right",class:"navi__icon")
    %li.navi__itemName
      %p= @item.name

app/views/shared/_sub_block.html.haml
.subBlock
  .firstSec
    %ul.subBlock__lists
      = link_to user_path(current_user) do
        %li.subBlock__list
          マイページ
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          やることリスト
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          いいね！一覧
          %span
            %i.fas.fa-chevron-right
      = link_to new_item_path do
        %li.subBlock__list
          出品する
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          出品した商品-出品中
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          出品した商品-取引中
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          出品した商品-売却済み
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          購入した商品-取引中
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          購入した商品-過去の取引
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          ニュース一覧
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          評価一覧
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          ガイド
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          お問い合わせ
          %span
            %i.fas.fa-chevron-right
  .secondSec
    %p.subBlock__listTtl
      メルペイ
    %ul.subBlock__lists
      = link_to "＃" do
        %li.subBlock__list
          売上・振込申請
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          ポイント
          %span
            %i.fas.fa-chevron-right
  .thirdSec
    %p.subBlock__listTtl
      設定
    %ul.subBlock__lists
      = link_to "＃" do
        %li.subBlock__list
          プロフィール
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          発送元・お届け先住所変更
          %span
            %i.fas.fa-chevron-right
      = link_to edit_card_path(current_user) do
        %li.subBlock__list
          カード登録
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          メール/パスワード
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          本人情報
          %span
            %i.fas.fa-chevron-right
      = link_to "＃" do
        %li.subBlock__list
          電話番号の確認
          %span
            %i.fas.fa-chevron-right
      = link_to destroy_user_session_path, method: 'delete' do
        %li.subBlock__list
          ログアウト
          %span
            %i.fas.fa-chevron-right