config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  
  #ユーザー登録のルーティング
  resources :signup do
    collection do
      get 'registration'
      get 'sms_confirmation'
      get 'address'
      get 'done'
    end
  end
  
  # ルート指定
  root 'tops#index'
  
  # ユーザーページのルーティング
  resources :users do
    resource :self_address
    resources :delivery_addresses
  end

  # 商品ページのルーティング
  resources :items do
    resources :likes
    resources :comments
    resources :images
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
    end
    # 購入
    resources :purchases, only: [:index] do
      collection do
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end

  # カード登録ページのルーティング
  resources :cards, only: [:create, :show, :edit] do
    collection do
      post 'delete', to: 'cards/current_user.id/delete'
      post 'show'
    end
    member do
      get 'confirmation'
    end
  end 
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true
  has_many :comments
  has_many :likes
  belongs_to :category
  belongs_to :buyer, optional: true, class_name: "User"
  belongs_to :seller, class_name: "User"

  validates_associated :images
  validates :images, presence: true
  validates :name, presence: true
  validates :explanation, presence: true
  validates :category_id, presence: true
  validates :size, presence: true
  validates :condition, presence: true
  validates :fee_which, presence: true
  validates :from_where, presence: true
  validates :delivery_date, presence: true
  validates :price, presence: true

  enum condition: { "新品、未使用": 1, "未使用に近い": 2, "目立った傷や汚れなし": 3, "やや傷や汚れあり": 4, "傷や汚れあり": 5, "全体的に状態が悪い": 6}, _prefix: true
  enum size: { "XXS以下": 1, "XS（SS）": 2, "S": 3, "M": 4, "L": 5, "XXL": 6}, _prefix: true
  enum fee_which: { "送料込み(出品者負担)": 1, "着払い(購入者負担)": 2}, _prefix: true
  enum delivery: { "未定": 1, "らくらくメルカリ便": 2, "ゆうメール": 3, "レターパック": 4, "普通郵便(定形、定形外)": 5, "クロネコヤマト": 6, "ゆうパック": 7, "クリックポスト": 8, "ゆうパケット": 9}, _prefix: true
  enum from_where: { 北海道: 1, 青森県: 2, 岩手県: 3, 宮城県: 4, 秋田県: 5, 山形県: 6, 福島県: 7, 東京都: 8, 神奈川県: 9, 埼玉県: 10, 千葉県: 11, 茨城県: 12, 栃木県: 13, 群馬県: 14, 山梨県: 15, 新潟県: 16, 長野県: 17, 富山県: 18, 石川県: 19, 福井県: 20, 愛知県: 21, 岐阜県: 22, 静岡県: 23, 三重県: 24, 大阪府: 25, 兵庫県: 26, 京都府: 27, 滋賀県: 28, 奈良県: 29, 和歌山県: 30, 鳥取県: 31, 島根県: 32, 岡山県: 33, 広島県: 34, 山口県: 35, 徳島県: 36, 香川県: 37, 愛媛県: 38, 高知県: 39, 福岡県: 40, 佐賀県: 41, 長崎県: 42, 熊本県: 43, 大分県: 44, 宮崎県: 45, 鹿児島県: 46, 沖縄県: 47}, _prefix: true
  enum delivery_date: { "1~2日で発送": 1, "2~3日で発送": 2, "4~7日で発送": 3},_prefix: true
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:index, :edit, :show, :confirm, :destroy, :update]
  before_action :set_category, only: [:index, :show, :destroy]

  def index
    @items = Item.page(params[:page]).per(12)
  end
  
  def show
  end

  def new
    @item = Item.new
    @item.images.new
    @parents = Category.all.order("id ASC").limit(13)

    #セレクトボックスの初期値設定
    @category_parent_array = ["---"]
      # データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
    end
  end

  # 以下全て、formatはjsonのみ
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      #セレクトボックスの初期値設定
      @category_parent_array = ["---"]
      # データベースから、親カテゴリーのみ抽出し、配列化
      Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
      render :new
    end
  end

  def confirm
  end

  def edit
    @parents = Category.all.order("id ASC").limit(13)
    #セレクトボックスの初期値設定
    @category_parent_array = []
      # データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
        @category_parent_array << parent.name
    end
  end
  # 以下全て、formatはjsonのみ
  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end
  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def update
    if @item.update(item_params)
      redirect_to item_path
    else
      @parents = Category.all.order("id ASC").limit(13)
      #セレクトボックスの初期値設定
      @category_parent_array = []
        # データベースから、親カテゴリーのみ抽出し、配列化
      Category.where(ancestry: nil).each do |parent|
          @category_parent_array << parent.name
      end
      render :edit
    end
  end

  def destroy
    if current_user.id == @item.seller_id
      @item.destroy
      redirect_to root_path
    else
      render :show, notice: '削除できませんでした'
    end
  end

  def search
    respond_to do |format|
      format.html
      format.json do
       @children = Category.find(params[:parent_id]).children
       #親ボックスのidから子ボックスのidの配列を作成してインスタンス変数で定義
      end
    end
  end

  private
  def item_params
    params.require(:item).permit(
      :name,
      :explanation, 
      :brand, 
      :condition, 
      :size, 
      :fee_which, 
      :from_where, 
      :delivery_date, 
      :price, 
      :category_id, 
      images_attributes: [:url, :_destroy, :id], 
    ).merge(seller_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def set_category
    @parents = Category.all.where(ancestry: nil)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_error-messages.html.haml
- if item.errors.any?
  - unless item.valid?
    - if errors = item.errors.full_messages_for(column.to_sym)
      %ul
        - errors.each do |error|
          %li=error

app/views/items/_form.html.haml
.itemsNew

  .itemsNew__header
    = link_to root_path do
      = image_tag 'logo.png', alt: 'FURIMA', class: 'itemsNew__logo'

  .itemsNew__body
    = form_for @item do |f|
      .itemsNew__container
        .itemsNew__title
          .itemsNew__subTitle
            出品画像
          .itemsNew__tag
            必須
        .itemsNew__photoExplanation 
          最大10枚までアップロードできます
        .sell-form.dropzone#item-dropzone
          %h2.sell-form__header
            商品情報を入力
          .sell-form-container
            %label.sell-form-container__label
              出品画像
            %span.sell-form-container__require
              必須
            #image-box
              #previews
                - if @item.persisted?
                  - @item.images.each_with_index do |image, i|
                    = image_tag image.url, data: { index: i }, width: "100", height: '100'

              = f.fields_for :images do |image|
                .js-file_group{data:{index: image.index}}
                  = image.file_field :url, class: "js-file img-add"

                - if @item.persisted?
                  = image.check_box :_destroy, data:{ index: image.index }, class: 'hidden-destroy'
                  
              - if @item.persisted?
                .js-file_group{data:{index:"@item.images.count"}}
                  = file_field_tag :url, name: "item[images_attributes][#{@item.images.count}][url]", class: 'js-file'
                  .js-remove 削除
            = render partial: 'error-messages', locals: { item: @item, column: "images"}
              

      .itemsNew__container
        .itemsNew__innerContainer
          .itemsNew__title
            .itemsNew__subTitle
              出品名
            .itemsNew__tag
              必須
          = f.text_field :name, placeholder: "40字まで", class: "itemsNew__inputBox"
          = render partial: 'error-messages', locals: { item: @item, column: "name"}
          
        .itemsNew__innerContainer
          .itemsNew__title
            .itemsNew__subTitle
              出品の説明
            .itemsNew__tag
              必須
          = f.text_area :explanation, class: "itemsNew__textareaBox", placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", rows: "7"
          = render partial: 'error-messages', locals: { item: @item, column: "explanation"}

      .itemsNew__container
        .itemsNew__mainTitle
          商品の詳細
        .itemsNew__innerContainer
          .listing-product-detail__category
            .itemsNew__title
              .itemsNew__subTitle
                カテゴリー
              .itemsNew__tag
                必須
            = f.select :category, @category_parent_array, {}, {class: 'listing-select-wrapper__box--select itemsNew__selectBox', id: 'parent_category'}
            .itemsNew__alert.displayNone
              選択してください
            = render partial: 'error-messages', locals: { item: @item, column: "category_id"}
        
        .itemsNew__innerContainer
          .itemsNew__title
            .itemsNew__subTitle
              サイズ
            .itemsNew__tag
              必須
          = f.select :size, Item.sizes.keys,{prompt: '選択してください'},class: "itemsNew__selectBox"
          .itemsNew__alert.displayNone
            選択してください
          .itemsEdit__alert
            = render partial: 'error-messages', locals: { item: @item, column: "size"}
        
        .itemsNew__innerContainer
          .itemsNew__title
            .itemsNew__subTitle
              ブランド
            .itemsNew__tag--gray
              任意
          =f.text_field :brand, placeholder: "入力してください", class: "itemsNew__inputBox"

        .itemsNew__innerContainer
          .itemsNew__title
            .itemsNew__subTitle
              商品の状態
            .itemsNew__tag
              必須
          = f.select :condition, Item.conditions.keys,{prompt: '選択してください'},class: "itemsNew__selectBox"
          .itemsNew__alert.displayNone
            選択してください
          = render partial: 'error-messages', locals: { item: @item, column: "condition"}

      .itemsNew__container
        .itemsNew__mainTitle
          配送について
        .itemsNew__innerContainer
          .itemsNew__title
            .itemsNew__subTitle
              配送料の負担
            .itemsNew__tag
              必須
          = f.select :fee_which, Item.fee_whiches.keys,{prompt: '選択してください'}, class: "itemsNew__selectBox"
          .itemsNew__alert.displayNone
            選択してください
          = render partial: 'error-messages', locals: { item: @item, column: "fee_which"}

        .itemsNew__innerContainer
          .itemsNew__title
            .itemsNew__subTitle
              発送元の地域
            .itemsNew__tag
              必須
          = f.select :from_where, Item.from_wheres.keys,{prompt: '選択してください'}, class: "itemsNew__selectBox"
          .itemsNew__alert.displayNone
            選択してください
          = render partial: 'error-messages', locals: { item: @item, column: "from_where"}

        .itemsNew__innerContainer
          .itemsNew__title
            .itemsNew__subTile
              発送までの日数
            .itemsNew__tag
              必須
          = f.select :delivery_date, Item.delivery_dates.keys,{prompt: '選択してください'}, class: "itemsNew__selectBox"
          .itemsNew__alert.displayNone
            選択してください
          = render partial: 'error-messages', locals: { item: @item, column: "delivery_date"}

      .itemsNew__container
        .itemsNew__mainTitle
          価格（¥300〜9,999,999）
        .itemsNew__sellContainer
          .itemsNew__title
            .itemsNew__subTitle
              販売価格
            .itemsNew__tag
              必須
          .itemsNew__sellPriceBox
            ¥
            = f.number_field :price, placeholder: "0", class: "itemsNew__inputBox--sellPrice", min: "300", max: "9999999", style: "text-align: right;"
        .itemsNew__alertInputBox
          .itemsNew__alertInputBox2.displayNone
            300以上9999999以下で入力してください

        .itemsNew__sellPrice
          .itemsNew__sellPrice--left
            販売手数料（10%）
          .itemsNew__sellPrice--right
            ー

        .itemsNew__priceProfit
          .itemsNew__sellPrice--left
            販売利益
          .itemsNew__priceProfit--right
            ー
        = render partial: 'error-messages', locals: { item: @item, column: "price"}

        .itemsNew__btnContainer
          .itemsNew__modalOpen
            = f.submit "出品", class:"itemsNew__sellBtn"
            %button{type: "submit", class: "itemsNew__sellBtn itemsNew__backBtn"}
              もどる

        .itemsNew__note
          禁止されている
          %span>
          = link_to('行為', {}, class: 'itemsNew__noteLink')
          %span>
          および
          %span>
          = link_to('出品物', {}, class: 'itemsNew__noteLink')
          %span>
          を必ずご確認ください。
          %span>
          = link_to('偽ブランド品', {}, class: 'itemsNew__noteLink')
          %span>
          や
          %span>
          = link_to('盗品物', {}, class: 'itemsNew__noteLink')
          %span>
          などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして
          %span>
          = link_to('加盟店規約', {}, class: 'itemsNew__noteLink')
          %span>
          に同意したことになります。

  .itemsNew__footer
    .itemsNew__footerTop
      %ul.itemsNew__footerUl
        %li.itemsNew__footerList
          = link_to('プライバシーポリシー', {}, class: 'itemsNew__footerList--link')
        %li.itemsNew__footerList
          = link_to('フリマ利用規約', {}, class: 'itemsNew__footerList--link')
        %li.itemsNew__footerList
          = link_to('特定商品に関する表記', {}, class: 'itemsNew__footerList--link')

    .itemsNew__footerLogo
      = image_tag 'logo-blue.png', alt: 'FURIMA', class: 'itemsNew__logo'

app/views/items/confirm.html.haml
%header.confirmHeader
  .headerLogo
    =link_to root_path do
      = image_tag "logo.png"
%main
  %section.confirmContainer
    .buyTitle
      %h1.buyTitle__text
        購入内容の確認
    .buyItem
      .buyItem__inner
        %ul.buyItem__inner__box
          %li.buyItem__inner__box__img
            = image_tag @item.images[0].url
            -# carrierwave導入したら下記に画像変更
            -# = @item.thumbnail
          %li.buyItem__inner__box__text
            %p.buyItem__inner__box__text__itemName
              = @item.name
            %ul.buyItem__inner__box__text__itemPrice
              %li.price
                = "#{@item.price}円"
              %li.feeTax
                （税込）送料込み
    %section.buyContent
      %form.buyForm
        %ul.buyForm__priceBox
          %li.buyForm__priceBox__text
            支払い金額
          %li.buyForm__priceBox__price
            = "#{@item.price}円"
        %ul.buyForm__payment
          %h3
            支払い方法
          %p
            =link_to "#" do
              =icon("fa","plus-square")
              登録してください
        %ul.buyForm__deliveryAddress
          %h4
            配送先
          %p
            =link_to "#" do
              =icon("fa","plus-square")
              登録してください
        .buyForm__Btn
          =link_to "購入する", item_purchases_path(@item)
          -# %button{type: "submit",class:"buyBtn"}
          -#   購入する
%footer.confirm
  .footerInner
    %ul.footerInner__navi
      %li
        = link_to "プライバシー"
      %li
        = link_to "FURIMA利用規約"
      %li
        = link_to "特定商取引に関する表記"
    .footerLogo
      = image_tag "logo-white.png"
    %p
      ©️FURIMA

app/views/items/destroy.html.haml
= render "shared/header", parents: @parents
%deletemain
  .deleteMain
    .deleteMain__box
      .deleteMain__box__text
        削除しました
      .deleteMain__box__btn
        =link_to root_path do
          トップページに戻る
    .deleteMain__footerLogo
      = image_tag 'logo-blue.png', alt: 'FURIMA', class: 'deleteMain__logo'
    .deleteMain__footerLogo__text
      ©︎FURIMA

app/views/items/index.html.haml
= render "shared/header", parents: @parents

= render "shared/navi"

%main.items
  .itemIndex
    .itemIndex__pickupCategory
      .itemIndex__pickupCategory__title
        %h1.itemIndex__pickupCategory__title__text
          メンズの商品一覧
      .itemIndex__pickupCategory__type
        %ul.itemIndex__pickupCategory__type__text
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              トップス
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              ジャケット/アウター
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              パンツ
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              靴
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              バッグ
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              スーツ
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              帽子
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              アクセサリー
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              小物
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              時計
          %li.itemIndex__pickupCategory__type__text__name
            = link_to "#" do
              水着

    .itemIndex__productList
      - @items.each do |item|
        .itemIndex__productList__items
          -if item.buyer_id > 0
            .itemIndex__productList__items__sold
              SOLD
          = link_to "items/#{item.id}" do
            = image_tag item.thumbnail
            .itemIndex__productList__items__text
              %h8.itemIndex__productList__items__text__name
                = item.name
              %ul.itemIndex__productList__items__text__box
                %li.itemIndex__productList__items__text__box__price
                  = "#{item.price}円"
                %li.itemIndex__productList__items__text__box__likes
                  = icon('fa','star',class:"productList__icon")
                  .itemIndex__productList__items__text__box__likes__volume
                    20
              %p.itemIndex__productList__items__text__tax
                (税込)

    = paginate(@items)

= render "shared/banner"
= render "shared/footer"

app/views/items/new.html.haml
= render partial: 'form'

app/views/items/show.html.haml
= render "shared/header", parents: @parents

= render "shared/navi"

%main.showItem
  .mainBox
    .mainBox__itemName
      = @item.name
    .mainBox__mainImage
      = image_tag @item.images[0].url
    %ul.mainBox__imageBox
      -@item.images.each do |i|
        - if i.url.present?
          %li.mainBox__imageBox__leftImage
            = image_tag i.url
    .mainBox__priceBox
      %h.mainBox__priceBox__itemPrice
        ="#{@item.price}円"
      %p.mainBox__priceBox__tax
        (税込)送料込み
    .mainBox__text
      =@item.explanation
    .mainBox__btn
      -if user_signed_in?
        -if  current_user.id == @item.seller_id
          =link_to edit_item_path(@item) do
            .mainBox__editBtn
              商品の編集
          .mainBox__destroyBtn#modal-open-btn
            商品の削除
          #overlay
            #modalWindow
              .modal-message-box
                %p 確認 
                本当に削除しますか？
              %button#modal-close-btn キャンセル
              =link_to item_path(@item),method: :delete ,id: 'item-delete-btn',class:'deleteBtn' do
                %button#delete-comformation-btn 削除する

        -else
          -if @item.buyer_id
            .mainBox__soldBtn
              SOLD OUT
          -else 
            = link_to confirm_item_path(@item) do
              .mainBox__buyBtn
                購入画面に進む

      -else
        -if @item.buyer_id
          .mainBox__soldBtn
            SOLD OUT
        -else 
          = link_to confirm_item_path(@item) do
            .mainBox__buyBtn
              購入画面に進む

    %table.mainTable
      %tr
        %th
          出品者
        %td
          = @item.seller.nickname
      %tr
        %th
          カテゴリー
        %td
          = link_to "#" do
            %p= @item.category.parent.parent.name
          = link_to "#" do
            %p= @item.category.parent.name    
          = link_to "#" do
            %p= @item.category.name
      %tr
        %th
          ブランド
        %td
          = @item.brand
      %tr
        %th
          商品のサイズ
        %td
          = @item.size
      %tr
        %th
          商品の状態
        %td
          = @item.condition
      %tr
        %th
          配送料の負担
        %td
          = @item.fee_which
      %tr
        %th
          発送元の地域
        %td
          = @item.from_where
      %tr
        %th
          発送日の目安
        %td
          = @item.delivery_date

    .mainBox__btns
      %ul.favoritBtn
        = icon("fa","star",class:"star__icon")
        %li.text
          お気に入り 0
      %ul.reportBtn
        = icon("fa","flag",class:"flag__icon")
        %li.text
          =link_to "#"do
            不適切な商品の通報
    

  .commentBox
    %textarea{type: "text",class:"comment__form"}
    .commentBox__Info
      .commentBox__Info__text
      相手のことを考え丁寧なコメントを心がけましょう。
      %br
      不快な言葉遣いなどは利用制限や退会処分となることがあります。
    %button{type: "submit",value:"コメントする",class:"commentBox__btn"}
      = icon("fa","comment",class:"comment__icon")
      コメントする

  %ul.page
    %li.page__front
      = link_to "#" do
        = icon("fa","chevron-left")
        前の商品
    %li.page__back
      = link_to "#" do
        後ろの商品
        = icon("fa","chevron-right",class:"navi__icon")

= render "shared/banner"

= render "shared/footer"