config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
  }
  
  #ユーザー登録のルーティング
  resources :signup do
    collection do
      get 'registration'
      get 'sms_confirmation'
      get 'address'
      get 'done'
    end
  end
  
  # ルート指定
  root 'tops#index'
  
  # ユーザーページのルーティング
  resources :users do
    resource :self_address
    resources :delivery_addresses
  end

  # 商品ページのルーティング
  resources :items do
    resources :likes
    resources :comments
    resources :images
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'confirm'
    end
    # 購入
    resources :purchases, only: [:index] do
      collection do
        post 'pay', to: 'purchases#pay'
        get 'done', to: 'purchases#done'
      end
    end
  end

  # カード登録ページのルーティング
  resources :cards, only: [:create, :show, :edit] do
    collection do
      post 'delete', to: 'cards/current_user.id/delete'
      post 'show'
    end
    member do
      get 'confirmation'
    end
  end 
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :get_payjp_info, only: [:new_create, :create, :delete, :show]
  before_action :set_parents, only: [:edit, :delete, :show, :confirmation]
  before_action :card, only: [:edit, :delete, :show]

  def edit
    if @card.present?
      redirect_to action: "show", id: current_user.id
    end
  end

  def create
    if params['payjp-token'].blank?
      redirect_to action: "edit", id: current_user.id
    else
      customer = Payjp::Customer.create(
      email: current_user.email,
      card: params['payjp-token'],
      metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        redirect_to action: "show"
      else
        redirect_to action: "edit", id: current_user.id
      end
    end
  end

  def delete
    if @card.present?
      customer = Payjp::Customer.retrieve(@card.customer_id)
      customer.delete
      @card.delete
    end
      redirect_to action: "edit", id: current_user.id
  end

  def show
    if @card.present?
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @default_card_information = customer.cards.retrieve(@card.card_id)
    else
      redirect_to action: "confirmation", id: current_user.id
    end
  end

  def confirmation
    card = current_user.cards
    redirect_to action: "show" if card.exists?
  end

  private
  def get_payjp_info
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
  end

  def set_parents
    @parents = Category.where(ancestry: nil)
  end

  def card
    @card = current_user.cards.first
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/confirmation.html.haml
= render "shared/header"
%main
  .commonContents
    = render "shared/sub_block"
    .mainBlock
      %h2.mainBlock__ttl
        支払い方法
      .mainBlock__content
        .mainBlock__content-inner
          %h3.mainBlock__subTtl クレジットカード一覧
          .add__card
            .payment__list__content
              = link_to edit_card_path(current_user.id), class: "formArea__btn" do
                %i
                = icon('fas', 'card', class: "card__icon")
                クレジットカードを追加する
        .payQuestion
          = link_to "支払い方法について", edit_card_path(1)
= render "shared/banner"
= render "shared/footer"

app/views/cards/edit.html.haml
= render "shared/header"
%main
  .commonContents
    = render "shared/sub_block"
    .mainBlock
      %h2.mainBlock__ttl
        クレジットカード情報入力
      .mainBlock__content
        .formArea
          = form_tag('/cards', method: :post, action: "create", id: 'charge-form',  name: "inputForm") do
            .formArea__num
              %p.form__txt
                カード番号
                %span.must
                  必須
              = text_field_tag "number", "", class: 'formArea-inputNum formArea-inputDef', placeholder: '半角数字のみ',maxlength: "16", type: "text", id: "card_number"
              %ul.cardsLists
                %li.cardList
                  = image_tag "visa.svg", class: "visa compLogo"
                %li.cardList
                  = image_tag "master-card.svg", class: "master-card compLogo"
                %li.cardList
                  = image_tag "saison-card.svg", class: "saison-card compLogo"
                %li.cardList
                  = image_tag "jcb.svg", class: "jcb compLogo"
                %li.cardList
                  = image_tag "american_express.svg", class: "american_express compLogo"
                %li.cardList
                  = image_tag "dinersclub.svg", class: "dinersclub compLogo"
                %li.cardList
                  = image_tag "discover.svg", class: "discover compLogo"
            .formArea__expiration
              %p.form__txt
                有効期限
                %span.must
                  必須
              .formArea__expiration-month-year
                %p.formArea__expiration-month
                  %select.formArea-inputDef#exp_month{name: "exp_month", type: "text"}
                    %option{value: ""} --
                    %option{value: "1"}01
                    %option{value: "2"}02
                    %option{value: "3"}03
                    %option{value: "4"}04
                    %option{value: "5"}05
                    %option{value: "6"}06
                    %option{value: "7"}07
                    %option{value: "8"}08
                    %option{value: "9"}09
                    %option{value: "10"}10
                    %option{value: "11"}11
                    %option{value: "12"}12
                    %i
                      = icon('fas', 'chevron-down')
                  %span 月
                %p.formArea__expiration-year
                  %select.formArea-inputDef#exp_year{name: "exp_year", type: "text"}
                    %option{value: ""} --
                    %option{value: "2019"}19
                    %option{value: "2020"}20
                    %option{value: "2021"}21
                    %option{value: "2022"}22
                    %option{value: "2023"}23
                    %option{value: "2024"}24
                    %option{value: "2025"}25
                    %option{value: "2026"}26
                    %option{value: "2027"}27
                    %option{value: "2028"}28
                    %option{value: "2029"}29
                    %i
                      = icon('fas', 'chevron-down')
                  %span  年
            .formArea__securityCode
              %p.form__txt
                セキュリティコード
                %span.must
                  必須
              = text_field_tag "cvc", "", class: "formArea__securityCode-code formArea-inputDef", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
              %p.formArea__securityCode-question
                カード裏面の番号とは？

            .formArea__bt#card_token#card_token
              = submit_tag "追加する", id: "token_submit", class: "formArea__btn"
        
= render "shared/banner"
= render "shared/footer"

app/views/cards/edit_test.html.haml
%section.chapter__container
  %h2.chapter__head クレジットカード情報入力
  = form_tag('/credit_card', method: :post, action: "create", id: 'charge-form',  name: "inputForm", class: "chapter__container__inner") do
    .form__main__container
      .form__content
        %label.payment__card カード番号
        %span.require__form 必須
        = text_field_tag "number", "", class: "number input__deafult", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
        .card__list
          .card__list__picture
      .form__content.top__margin
        %label.payment__card 有効期限
        %span.require__form 必須
        .select__box.top__margin
          .select__box__half
            %select.select__default#exp_month{name: "exp_month", type: "text"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %i
              = icon('fas', 'chevron-down')
            %span 月
          .select__box__half
            .icon
            %select.select__default#exp_year{name: "exp_year", type: "text"}
              %option{value: ""} --
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
              %i
                = icon('fas', 'chevron-down')
            %span  年
      .form__content.top__margin
        %label セキュリティーコード
        %span.require__form 必須
        = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面4桁もしくは3桁の番号", maxlength: "4", id: "cvc"
        .single__code
          .single__code__text
          %span.form__question ? 
          %span カードの裏面の番号とは？
      #card_token
      = submit_tag "追加する", id: "token_submit", class: "top__margin"

app/views/cards/show.html.haml
= render "shared/header"
%main
  .commonContents
    = render "shared/sub_block"
    .mainBlock
      %h2.mainBlock__ttl
        支払い方法
      .mainBlock__content
        .mainBlock__content-inner
          %h3.mainBlock__subTtl クレジットカード一覧
          .card__info 
            -if @card.present?
              .card__number 
                = "**** **** **** " + @default_card_information.last4
              .card__delete-btn 
                = link_to '削除する', delete_cards_path, method: :post
            -else
              %p.card__add-btn 
                = link_to 'カードを追加する', edit_card_path, method: :get
        .payQuestion
          = link_to "支払い方法について", edit_card_path(1);

app/views/cards/sub.html.haml
.mainBlock
      %h2.mainBlock__ttl
        クレジットカード情報入力
      .formArea
        = form_for user do |c|
          .formArea__num
            =c.label :カード番号, class: 'form__txt'
            %span.must
              必須
            =c.text_field :card_number, type: 'text', class: 'input-number', placeholder: '半角数字のみ', maxlength: "16"
            %ul.cardsLists
              %li.cardList
                = f.label :有効期限, class: 'label'
                %span 必須
                .cardList__expire-wrap
                  = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{} , class: 'input-expire'
                  %span.expire-text 月
                  %br
                .cardList__expire-wrap
                  = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]],{} , class: 'input-expire'
                  %span.expire-text 年
          .formArea__expiration
            %p.form__txt
              有効期限
              %span.must
                必須
            .formArea__expiration-month-year
              %p.formArea__expiration-month
                %input
                月
              %p.formArea__expiration-year
                %input
                年
          .formArea__securityCode
            = c.label :セキュリティコード, class: 'label'
            %span 必須
            = c.text_field :cvc, type: 'text', class: 'input-number', placeholder: 'カード背面4桁もしくは3桁の番号', maxlength: "4"
            %p.formArea__securityCode-question
              カード裏面の番号とは？
          .formArea__btn
            = f.submit '追加する', class: 'content-bottom--add-btn', id: 'token_submit'